name: Java CI with Maven

on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml
      env:
        APP_DB_URI: jdbc:postgresql://localhost:5432/postgres
        APP_DB_USER: postgres
        APP_DB_PW: postgres
        HIBERNATE_DDL: create-drop
